### ISSUE TITLE
change your program now shows the com ports  and abel to choose 1 at the start 

### ISSUE THREAD

**Issue by tenij000** [brad28b/meshtastic-cli-receive-text#2] opened 2024-11-18 18:27 UTC
import time
import sys
from pubsub import pub
from meshtastic.serial_interface import SerialInterface
from meshtastic import portnums_pb2
import serial.tools.list_ports

def list_com_ports():
    # List available COM ports
    ports = list(serial.tools.list_ports.comports())
    if not ports:
        print("No devices found.")
        sys.exit(1)

    print("Available COM ports:")
    for i, port in enumerate(ports):
        print(f"{i + 1}: {port.device}")
    return ports

def select_com_port(ports):
    # Get user's choice of COM port
    selection = input("Enter the number of the device to use: ")
    try:
        selected_device = ports[int(selection) - 1].device
    except (IndexError, ValueError):
        print("Invalid selection.")
        sys.exit(1)
    return selected_device

def get_node_info(serial_port):
    print("Initializing SerialInterface to get node info...")
    local = SerialInterface(serial_port)
    node_info = local.nodes
    local.close()
    print("Node info retrieved.")
    return node_info

def parse_node_info(node_info):
    print("Parsing node info...")
    nodes = []
    for node_id, node in node_info.items():
        nodes.append({
            'num': node_id,
            'user': {
                'shortName': node.get('user', {}).get('shortName', 'Unknown')
            }
        })
    print("Node info parsed.")
    return nodes

def on_receive(packet, interface, node_list):
    try:
        if packet['decoded']['portnum'] == 'TEXT_MESSAGE_APP':
            message = packet['decoded']['payload'].decode('utf-8')
            fromnum = packet['fromId']
            shortname = next((node['user']['shortName'] for node in node_list if node['num'] == fromnum), 'Unknown')
            print(f"{shortname}: {message}")
    except KeyError:
        pass  # Ignore KeyError silently
    except UnicodeDecodeError:
        pass  # Ignore UnicodeDecodeError silently

def main():
    # List and select a serial port
    ports = list_com_ports()
    serial_port = select_com_port(ports)
    print(f"Using serial port: {serial_port}")

    # Retrieve and parse node information
    node_info = get_node_info(serial_port)
    node_list = parse_node_info(node_info)

    # Print node list for debugging
    print("Node List:")
    for node in node_list:
        print(node)

    # Subscribe the callback function to message reception
    def on_receive_wrapper(packet, interface):
        on_receive(packet, interface, node_list)

    pub.subscribe(on_receive_wrapper, "meshtastic.receive")
    print("Subscribed to meshtastic.receive")

    # Set up the SerialInterface for message listening
    local = SerialInterface(serial_port)
    print("SerialInterface setup for listening.")

    # Keep the script running to listen for messages
    try:
        while True:
            sys.stdout.flush()
            time.sleep(1)  # Sleep to reduce CPU usage
    except KeyboardInterrupt:
        print("Script terminated by user")
        local.close()

if __name__ == "__main__":
    main()

**Comment by brad28b** [comment] 2024-11-19 04:02
Please fork the repository rather than open an issue, as this is not a bug. Closing

**Closed** 2024-11-19 04:12 UTC
